### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by jmrichardson** [christophmark/bayesloop#36]
Hi, 

I am following along the [example](https://github.com/christophmark/bayesloop/blob/master/docs/source/examples/stockmarketfluctuations.ipynb):

```
for r in tqdm_notebook(logReturns):
    S.step(r)
```

It is taking about 1.5 seconds for each step to process.  Is this normal or did I do something wrong?  I have minute data and about 1M prices of historical data.  Would I need to send all of them into the step function?    I am sorry but I am new to probabilistic programming and bayesloop.  Thanks for any help/guidance.

**Comment by christophmark** [comment]
Sorry for the late reply. If you want to do an online-analysis that is guaranteed to give the same result on past data as in live mode, you need to pass the data step by step, yes. But you can for example reduce the number of grid points on the parameter grid to speed up the analysis. Or you can resample your data to e.g. 5min-bars...
