### ISSUE TITLE
bayesloop module fails to load, pythin 3.7.7 64-bit

### ISSUE THREAD

**Issue by amilenovic** [christophmark/bayesloop#37]
I wanted to try out the bayesloop. I followed the installation instructions in the documentation, but module import failed:

```
Python 3.7.7 (default, May  6 2020, 11:45:54) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import bayesloop
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\workspace\tools\Miniconda3\lib\site-packages\bayesloop\__init__.py", line 4, in <module>
    from .core import Study, HyperStudy, ChangepointStudy, OnlineStudy
  File "D:\workspace\tools\Miniconda3\lib\site-packages\bayesloop\core.py", line 15, in <module>
    from scipy.misc import factorial
ImportError: cannot import name 'factorial' from 'scipy.misc' (D:\workspace\tools\Miniconda3\lib\site-packages\scipy\misc\__init__.py)
```

I tried to resolve the problem, following https://stackoverflow.com/questions/56283294/importerror-cannot-import-name-factorial but that didn't resolve.

Any idea on how to overcome this issue?

**Comment by christophmark** [comment]
@amilenovic Sorry for the delayed reply, try to install from current `master`, I fixed those imports by now (`factorial` and others have been moved to `scipy.special`).

**Comment by christophmark** [comment]
This is finally fixed now not only on master, but also in the new 1.5.3 release.
